### ISSUE TITLE
[Login Issues]  HTTPSConnection.init() got an unexpected keyword argument 'key_file'

### ISSUE THREAD

**Issue by mugi-jiichan** [Nandaka/PixivUtil2#1338]
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

Hi,

my Linux PC was off for two days, and I've just upgraded to KDE/Plasma 6. Now, PU2 stopped working. I've reinstalled all python packages to meet the requirements, however can now longer log into pixiv with PU2.

PU2 shows the error message when it tries to connect:

TypeError: HTTPSConnection.__init__() got an unexpected keyword argument 'key_file'

So far, I've updated the password/cookie as suggested through Chromium, and double-checked if the useragent was set to the "Mozilla/5.0" stub that worked two days ago.

It's actually the last application that doesn't work for me though I had to fix up stuff the whole day. It might be a simple thing but I can't make heads and tails of it atm...

Can you help, please?

I've attached the log, my config and the list of python modules.

### Steps to Reproduce

1. Start PU2 after the Plasma 6 update.

**Expected behavior:** Auto-login works.

**Actual behavior:** Returns TypeError: HTTPSConnection.__init__() got an unexpected keyword argument 'key_file' and instantly goes into repeated two seconds loop that only restarts.

**Log file:** 
[pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/15366014/pixivutil.log)
[config_ini.txt](https://github.com/Nandaka/PixivUtil2/files/15366057/config_ini.txt)
[pip_list.txt](https://github.com/Nandaka/PixivUtil2/files/15366065/pip_list.txt)

### Versions

cloned from master, returns as 20230105

**Comment by mugi-jiichan** [comment]
Is it because I run it in a python 3.12 environment?

I've got it to work in Debian with python 3.11...

**Comment by mugi-jiichan** [comment]
Yeah it's python 3.12...

I've got it to work on a docker container now. The image falls even back to 3.10 - it works there.
